---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-12-fcce073da4f4> in <module>
      6 name_pass_map = dict(zip(final_df['Id'], zip(grouped['Name'], grouped['SCB_PSID'])))
      7 
----> 8 final_df['Name_Group'] = final_df['Id'].map(lambda x : name_pass_map[x][0])
      9 final_df['SCB_PSID_Group'] = final_df['Id'].map(lambda x : name_pass_map[x][1])

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py in map(self, arg, na_action)
   3968         dtype: object
   3969         """
-> 3970         new_values = super()._map_values(arg, na_action=na_action)
   3971         return self._constructor(new_values, index=self.index).__finalize__(
   3972             self, method="map"

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\base.py in _map_values(self, mapper, na_action)
   1158 
   1159         # mapper is a function
-> 1160         new_values = map_f(values, mapper)
   1161 
   1162         return new_values

pandas\_libs\lib.pyx in pandas._libs.lib.map_infer()

<ipython-input-12-fcce073da4f4> in <lambda>(x)
      6 name_pass_map = dict(zip(final_df['Id'], zip(grouped['Name'], grouped['SCB_PSID'])))
      7 
----> 8 final_df['Name_Group'] = final_df['Id'].map(lambda x : name_pass_map[x][0])
      9 final_df['SCB_PSID_Group'] = final_df['Id'].map(lambda x : name_pass_map[x][1])

KeyError: 10
